import {bodyJson,HTML_HEADERS,HttpError,json,nowIso,sanitizePublicError} from './lib.js';
import {authState,isAuthConfigured,login,logout,requireAdmin} from './auth.js';
import {loginHtml} from './auth-ui.js';
import {addMetric,briefing,createLead,createStudent,growthReport,listLeads,listRisks,recruitmentContent,recruitmentPerformance,recruitmentPlan,recruitmentTargets,recordCampaignEvent,setRecruitmentTarget,studentCard,updateLeadStage} from './services.js';
import {createPromoMission,createPromoPost,getAcademyProfile,listPromoAssets,listPromoPosts,promoAssetObject,promoDashboard,saveAcademyProfile} from './promo-v2.js';
import {createMissionProductionRun,createPromoProductionRun,generateOrReusePromoImage,processPromoProductionRun,promoProductionRun,recoverPromoProductionRun} from './promo-engine.js';
import {cleanupP3Fixtures} from './cleanup.js';
import {appHtml} from './ui-v4.js';
import {CLIENT_JS} from './client-v4.js';
const match=(path,re)=>path.match(re);
const APP_HTML_HEADERS={...HTML_HEADERS,"content-security-policy":"default-src 'none'; style-src 'unsafe-inline'; script-src 'self'; connect-src 'self'; img-src 'self' data: blob:; font-src 'self' data:; base-uri 'none'; form-action 'self'; frame-ancestors 'none'"};
const JS_HEADERS={"content-type":"application/javascript; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff","referrer-policy":"no-referrer","strict-transport-security":"max-age=31536000; includeSubDomains"};
function securedAppHtml(csrf){const safe=String(csrf||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));return appHtml().replace('<meta name="csrf-token" content="">','<meta name="csrf-token" content="'+safe+'">');}
export default {async fetch(request,env){try{const url=new URL(request.url),path=url.pathname;
if((path==='/health'||path==='/healthz')&&request.method==='GET')return json({ok:true,service:'ai-director-office',version:env.APP_VERSION||'0.6.0',db:Boolean(env.DB),ai:Boolean(env.AI),r2:Boolean(env.PROMO_ASSETS),auth:isAuthConfigured(env),promoEngine:'embedded-p1-style-v1',timestamp:nowIso()});
if(path==='/preflight'&&request.method==='GET'){const ok=Boolean(env.DB)&&Boolean(env.AI)&&Boolean(env.PROMO_ASSETS)&&isAuthConfigured(env);return json({ok,checks:{worker:true,d1:Boolean(env.DB),workersAI:Boolean(env.AI),r2:Boolean(env.PROMO_ASSETS),adminAuth:isAuthConfigured(env),embeddedPromoEngine:true},version:env.APP_VERSION||'0.6.0'},ok?200:503)}
if(path==='/auth/status'&&request.method==='GET')return json({ok:true,data:await authState(request,env)});if(path==='/auth/login'&&request.method==='POST')return await login(request,env);if(path==='/auth/logout'&&request.method==='POST')return logout();if(path==='/app.js'&&request.method==='GET')return new Response(CLIENT_JS,{status:200,headers:JS_HEADERS});
if(path==='/'&&request.method==='GET'){const state=await authState(request,env);if(!state.configured)return new Response(loginHtml(false),{status:503,headers:HTML_HEADERS});if(!state.authenticated)return new Response(loginHtml(true),{status:200,headers:HTML_HEADERS});return new Response(securedAppHtml(state.csrf),{status:200,headers:APP_HTML_HEADERS})}
if(!env.DB)throw new HttpError(503,'DB_NOT_BOUND');if(path.startsWith('/api/'))await requireAdmin(request,env,{mutation:!['GET','HEAD'].includes(request.method)});
if(path==='/api/briefing'&&request.method==='GET')return json({ok:true,data:await briefing(env)});if(path==='/api/risks'&&request.method==='GET')return json({ok:true,data:await listRisks(env)});let m=match(path,/^\/api\/students\/([^/]+)$/);if(m&&request.method==='GET')return json({ok:true,data:await studentCard(env,decodeURIComponent(m[1]))});if(path==='/api/students'&&request.method==='POST')return json({ok:true,data:await createStudent(env,request)},201);m=match(path,/^\/api\/students\/([^/]+)\/metrics$/);if(m&&request.method==='POST')return json({ok:true,data:await addMetric(env,request,decodeURIComponent(m[1]))},201);if(path==='/api/growth-report'&&request.method==='POST')return json({ok:true,data:await growthReport(env,await bodyJson(request))},201);
if(path==='/api/leads'&&request.method==='GET')return json({ok:true,data:await listLeads(env)});if(path==='/api/leads'&&request.method==='POST')return json({ok:true,data:await createLead(env,request)},201);m=match(path,/^\/api\/leads\/([^/]+)\/stage$/);if(m&&request.method==='POST')return json({ok:true,data:await updateLeadStage(env,request,decodeURIComponent(m[1]))});
if(path==='/api/recruitment/targets'&&request.method==='GET')return json({ok:true,data:await recruitmentTargets(env)});if(path==='/api/recruitment/targets'&&request.method==='POST')return json({ok:true,data:await setRecruitmentTarget(env,request)},201);if(path==='/api/recruitment/plan'&&request.method==='POST')return json({ok:true,data:await recruitmentPlan(env,await bodyJson(request))},201);if(path==='/api/recruitment/content'&&request.method==='POST')return json({ok:true,data:await recruitmentContent(env,await bodyJson(request))},201);if(path==='/api/recruitment/event'&&request.method==='POST')return json({ok:true,data:await recordCampaignEvent(env,request)},201);if(path==='/api/recruitment/performance'&&request.method==='GET')return json({ok:true,data:await recruitmentPerformance(env)});
if(path==='/api/promo/dashboard'&&request.method==='GET')return json({ok:true,data:await promoDashboard(env)});if(path==='/api/promo/profile'&&request.method==='GET')return json({ok:true,data:await getAcademyProfile(env)});if(path==='/api/promo/profile'&&request.method==='POST')return json({ok:true,data:await saveAcademyProfile(env,request)});if(path==='/api/promo/mission'&&request.method==='POST')return json({ok:true,data:await createPromoMission(env,await bodyJson(request))},201);if(path==='/api/promo/assets'&&request.method==='GET')return json({ok:true,data:await listPromoAssets(env)});if(path==='/api/promo/assets/generate'&&request.method==='POST')return json({ok:true,data:await generateOrReusePromoImage(env,await bodyJson(request))},201);m=match(path,/^\/api\/promo\/assets\/([^/]+)$/);if(m&&request.method==='GET')return await promoAssetObject(env,decodeURIComponent(m[1]));if(path==='/api/promo/posts'&&request.method==='GET')return json({ok:true,data:await listPromoPosts(env)});if(path==='/api/promo/posts'&&request.method==='POST')return json({ok:true,data:await createPromoPost(env,await bodyJson(request))},201);
if(path==='/api/promo/runs'&&request.method==='POST')return json({ok:true,data:await createPromoProductionRun(env,await bodyJson(request))},201);m=match(path,/^\/api\/promo\/missions\/([^/]+)\/run$/);if(m&&request.method==='POST')return json({ok:true,data:await createMissionProductionRun(env,decodeURIComponent(m[1]))},201);m=match(path,/^\/api\/promo\/runs\/([^/]+)$/);if(m&&request.method==='GET')return json({ok:true,data:await promoProductionRun(env,decodeURIComponent(m[1]))});m=match(path,/^\/api\/promo\/runs\/([^/]+)\/process$/);if(m&&request.method==='POST'){const b=await bodyJson(request);return json({ok:true,data:await processPromoProductionRun(env,decodeURIComponent(m[1]),{max_items:b.max_items})})}m=match(path,/^\/api\/promo\/runs\/([^/]+)\/recover$/);if(m&&request.method==='POST')return json({ok:true,data:await recoverPromoProductionRun(env,decodeURIComponent(m[1]))});if(path==='/api/internal/p3-cleanup'&&request.method==='POST')return json({ok:true,data:await cleanupP3Fixtures(env)});
return json({ok:false,error:'NOT_FOUND',path},404)}catch(error){const safe=sanitizePublicError(error);return json(safe.body,safe.status)}}};
