import {CLIENT_JS as V8} from './client-v8.js';

const OLD_LOAD_LEADS=`async function loadLeads(){try{const rows=await api('/api/leads');$('leadList').innerHTML=rows.filter(l=>!['ENROLLED','LOST'].includes(l.status)).map(l=>'<div class="row"><div class="rowhead"><b>'+esc(l.child_name)+' · '+esc(l.grade||'')+'</b><span class="pill yellow">'+esc(l.status)+'</span></div><div class="sub">'+esc(l.goal||'목표 미입력')+' · '+esc(l.source||'유입 미상')+'<br>후속: '+esc(l.followup_due_at||'미정')+'</div></div>').join('')||'<div class="empty">진행 중인 상담이 없습니다.</div>'}catch(e){$('leadList').innerHTML='<div class="empty">'+esc(friendly(e))+'</div>'}}`;

const NEW_LOAD_LEADS=`const LEAD_STATUS_KO={NEW:'신규문의',CONTACTED:'연락완료',CONSULTED:'상담완료',TRIAL:'체험중',ENROLLED:'등록완료',LOST:'종료'};\nfunction leadNext(status){return status==='NEW'?['CONTACTED','연락완료']:status==='CONTACTED'?['CONSULTED','상담완료']:status==='CONSULTED'?['TRIAL','체험 시작']:status==='TRIAL'?['ENROLLED','등록 완료']:null}\nasync function changeLeadStage(button){const id=button?.dataset?.leadId||'',status=button?.dataset?.leadStage||'';if(!id||!status)return;const label=button.textContent;button.disabled=true;button.textContent='처리 중…';try{await post('/api/leads/'+encodeURIComponent(id)+'/stage',{status});toast('상담 상태를 '+(LEAD_STATUS_KO[status]||status)+'로 변경했습니다.');await Promise.all([loadLeads(),loadBrief()])}catch(e){toast(friendly(e));button.disabled=false;button.textContent=label}}\nasync function loadLeads(){try{const rows=await api('/api/leads'),active=rows.filter(l=>!['ENROLLED','LOST'].includes(l.status));$('leadList').innerHTML=active.map(l=>{const next=leadNext(l.status),statusKo=LEAD_STATUS_KO[l.status]||l.status;return '<div class="row" data-lead-row="'+esc(l.id||'')+'"><div class="rowhead"><b>'+esc(l.child_name)+' · '+esc(l.grade||'')+'</b><span class="pill yellow">'+esc(statusKo)+'</span></div><div class="sub">'+esc(l.goal||'목표 미입력')+' · '+esc(l.source||'유입 미상')+'<br>후속: '+esc(l.followup_due_at||'미정')+'</div><div style="display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end;margin-top:10px">'+(next?'<button class="secondary" type="button" data-lead-id="'+esc(l.id||'')+'" data-lead-stage="'+next[0]+'">'+next[1]+'</button>':'')+'<button class="ghost" type="button" data-lead-id="'+esc(l.id||'')+'" data-lead-stage="LOST">종료</button></div></div>'}).join('')||'<div class="empty">진행 중인 상담이 없습니다.</div>';document.querySelectorAll('[data-lead-stage]').forEach(b=>b.onclick=()=>changeLeadStage(b))}catch(e){$('leadList').innerHTML='<div class="empty">'+esc(friendly(e))+'</div>'}}`;

const WITH_LEADS=V8.replace(OLD_LOAD_LEADS,NEW_LOAD_LEADS);
if(WITH_LEADS===V8)throw new Error('LEAD_STAGE_CARD_PATCH_MISSING');

export const CLIENT_JS=WITH_LEADS;
