export const CLIENT_JS=String.raw`(()=>{
'use strict';
const $=id=>document.getElementById(id),csrf=document.querySelector('meta[name="csrf-token"]')?.content||'';
let currentMission=null,currentNeeds=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const val=id=>($(id)?.value??'').trim();
const ERROR_KO={NAME_REQUIRED:'학생 이름을 입력해주세요.',GRADE_REQUIRED:'학년을 입력해주세요.',PROGRAM_REQUIRED:'과정을 선택해주세요.',CHILD_NAME_REQUIRED:'학생 이름을 입력해주세요.',INVALID_PROGRAM:'과정을 다시 선택해주세요.',TARGET_SEGMENT_REQUIRED:'모집 대상을 입력해주세요.',PURPOSE_REQUIRED:'이미지 용도를 입력해주세요.',PROMO_MISSION_NOT_FOUND:'홍보작전을 먼저 만들어주세요.',IMAGE_EMPTY_RESPONSE:'이미지 생성에 실패했습니다. 다시 시도해주세요.',PROMO_ASSETS_NOT_BOUND:'홍보 이미지 저장소 연결을 확인해주세요.',AUTH_REQUIRED:'로그인이 만료되었습니다. 다시 로그인해주세요.',INTERNAL_ERROR:'처리 중 문제가 생겼습니다. 잠시 후 다시 시도해주세요.'};
const friendly=e=>ERROR_KO[e?.message]||String(e?.message||'처리하지 못했습니다.').replaceAll('_',' ');
const toast=text=>{const t=$('toast');if(!t)return;t.textContent=text;t.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>t.classList.remove('show'),2400)};
const msg=(id,text,ok=true)=>{const el=$(id);if(!el)return;el.className=ok?'success':'error';el.textContent=text};
async function api(path,opt={}){const method=String(opt.method||'GET').toUpperCase(),headers=new Headers(opt.headers||{});headers.set('accept','application/json');if(!['GET','HEAD','OPTIONS'].includes(method)){headers.set('x-csrf-token',csrf);headers.set('content-type','application/json')}const r=await fetch(path,{...opt,headers,cache:'no-store'});if((r.headers.get('content-type')||'').startsWith('image/'))return r;const d=await r.json().catch(()=>({ok:false,error:'INVALID_RESPONSE'}));if(r.status===401){location.replace('/');throw new Error('AUTH_REQUIRED')}if(!r.ok||d.ok===false)throw new Error(d.detail||d.error||('HTTP '+r.status));return d.data??d}
const post=(p,b)=>api(p,{method:'POST',body:JSON.stringify(b)});
function seoulDate(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const x=Object.fromEntries(parts.map(p=>[p.type,p.value]));return x.year+'-'+x.month+'-'+x.day}
function setView(name){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name));if(name==='students')loadRisks();if(name==='leads')loadLeads();if(name==='recruitment')loadPromo();window.scrollTo({top:0,behavior:'smooth'})}
async function health(){try{const h=await api('/health');$('systemStatus').textContent='D1 · Workers AI · 홍보자산 · 보안 연결 정상 · v'+h.version}catch{$('systemStatus').textContent='시스템 연결을 다시 확인해주세요'}}
async function loadBrief(){try{const d=await api('/api/briefing'),c=d.counts;$('kStudents').textContent=c.students;$('kRisk').textContent=c.risk_red;$('kYellow').textContent=c.risk_yellow;$('kFollow').textContent=c.followups_due;$('kLeads').textContent=c.open_leads;$('kSeats').textContent=c.open_seats??0;$('briefTime').textContent='최근 갱신 '+new Date(d.generated_at).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit'});$('actions').innerHTML=(d.top_actions.length?d.top_actions:[{title:'긴급 작업이 없습니다',detail:'오늘의 학생 변화와 상담 일정을 확인하세요.'}]).map((a,i)=>'<div class="row"><div class="rowhead"><b>'+(i+1)+'. '+esc(a.title)+'</b></div><div class="sub">'+esc(a.detail||'')+'</div></div>').join('');window.__AI_OFFICE_DATA_READY__=true}catch(e){$('actions').innerHTML='<div class="empty">'+esc(friendly(e))+'</div>'}}
function riskRow(r){const color=r.band==='RED'?'red':r.band==='YELLOW'?'yellow':'green',label=r.band==='RED'?'위험':r.band==='YELLOW'?'관심':'안정';return '<div class="row"><div class="rowhead"><b>'+esc(r.student?.name||'학생')+' · '+esc(r.student?.grade||'')+'</b><span class="pill '+color+'">'+label+'</span></div><div class="sub">위험점수 '+Number(r.score||0)+' · 신뢰도 '+esc(r.confidence||'LOW')+'<br>'+esc((r.reasons||[])[0]||'뚜렷한 위험 신호 없음')+'</div></div>'}
async function loadRisks(){try{const rows=await api('/api/risks');$('studentRisks').innerHTML=rows.map(riskRow).join('')||'<div class="empty">등록된 학생이 없습니다.</div>'}catch(e){$('studentRisks').innerHTML='<div class="empty">'+esc(friendly(e))+'</div>'}}
async function loadLeads(){try{const rows=await api('/api/leads');$('leadList').innerHTML=rows.filter(l=>!['ENROLLED','LOST'].includes(l.status)).map(l=>'<div class="row"><div class="rowhead"><b>'+esc(l.child_name)+' · '+esc(l.grade||'')+'</b><span class="pill yellow">'+esc(l.status)+'</span></div><div class="sub">'+esc(l.goal||'목표 미입력')+' · '+esc(l.source||'유입 미상')+'<br>후속: '+esc(l.followup_due_at||'미정')+'</div></div>').join('')||'<div class="empty">진행 중인 상담이 없습니다.</div>'}catch(e){$('leadList').innerHTML='<div class="empty">'+esc(friendly(e))+'</div>'}}
function renderNeeds(needs=[]){currentNeeds=needs;$('assetNeeds').innerHTML=needs.length?needs.map((n,i)=>'<div class="need"><div><b>'+esc(n.purpose)+'</b><div class="sub">'+esc(n.channel)+' · '+n.width+'×'+n.height+(n.required?' · 필수':' · 선택')+'</div></div><button class="secondary" data-gen-asset="'+i+'">이미지 만들기</button></div>').join(''):'<div class="empty">제작물이 아직 없습니다.</div>';document.querySelectorAll('[data-gen-asset]').forEach(b=>b.onclick=()=>generateAsset(Number(b.dataset.genAsset)))}
function renderMissing(items=[]){$('missingProfile').innerHTML=items.length?items.map(x=>'<div class="row"><b>'+esc(x)+'</b><div class="sub">이 정보가 있으면 홍보물이 더 정확해집니다.</div></div>').join(''):'<div class="row"><span class="pill green">준비 완료</span><div class="sub">기본 홍보정보가 충분합니다.</div></div>'}
function renderAssets(assets=[]){$('assetGallery').innerHTML=assets.length?assets.map(a=>'<div class="asset"><img src="'+esc(a.url)+'" alt="'+esc(a.purpose||'홍보 이미지')+'"><div><b>'+esc(a.purpose||'홍보 이미지')+'</b><br>'+esc(a.channel||'')+' · '+(a.width||'')+'×'+(a.height||'')+'</div></div>').join(''):'<div class="empty">아직 생성된 홍보 이미지가 없습니다.</div>'}
function renderPosts(posts=[]){$('promoPosts').innerHTML=posts.length?posts.map(p=>'<div class="row"><div class="rowhead"><b>'+esc(p.title||p.channel)+'</b><span class="pill green">'+esc(p.status)+'</span></div><div class="sub">'+esc(p.format)+' · '+esc(p.created_at||'')+'</div></div>').join(''):'<div class="empty">아직 만든 게시물이 없습니다.</div>'}
async function loadPromo(){try{const d=await api('/api/promo/dashboard');$('pAcademy').value=d.profile?.academy_name||'';$('pNeighborhood').value=d.profile?.neighborhood||'';$('pCta').value=d.profile?.consultation_cta||'';$('pNaver').value=d.profile?.naver_blog_url||'';$('pInstagram').value=d.profile?.instagram_handle||'';$('pDaangn').value=d.profile?.daangn_profile||'';renderMissing(d.missing_profile||[]);if(d.latest_mission){currentMission=d.latest_mission.id;$('missionResult').style.display='block';$('missionResult').textContent=d.latest_mission.mission_text;renderNeeds(d.latest_mission.needs||[])}renderAssets((d.assets||[]).map(a=>({...a,url:'/api/promo/assets/'+encodeURIComponent(a.id)})));renderPosts(d.posts||[])}catch(e){toast(friendly(e))}}
async function generateAsset(i){const n=currentNeeds[i];if(!currentMission||!n)return;const buttons=[...document.querySelectorAll('[data-gen-asset]')];const b=buttons.find(x=>Number(x.dataset.genAsset)===i);if(b){b.disabled=true;b.textContent='이미지 생성 중…'}try{await post('/api/promo/assets/generate',{mission_id:currentMission,purpose:n.purpose,channel:n.channel,width:n.width,height:n.height,prompt_hint:n.prompt_hint});toast('홍보 이미지가 만들어졌습니다.');await loadPromo()}catch(e){toast(friendly(e))}finally{if(b){b.disabled=false;b.textContent='이미지 만들기'}}}
async function makePost(channel){if(!currentMission){toast('먼저 이번 주 홍보작전을 만들어주세요.');return}const box=$('postResult');box.style.display='block';box.textContent='채널에 맞는 완성 원고를 만들고 있습니다…';try{const d=await post('/api/promo/posts',{mission_id:currentMission,channel});box.textContent=d.body;await loadPromo();toast(d.channel_label+' 홍보물이 완성됐습니다.')}catch(e){box.textContent='생성 실패: '+friendly(e)}}
function bind(){
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>$(b.dataset.toggle)?.classList.toggle('open'));
 $('refreshAll').onclick=async()=>{await Promise.allSettled([health(),loadBrief(),loadRisks(),loadLeads(),loadPromo()]);toast('최신 상태로 갱신했습니다.')};$('logout').onclick=async()=>{try{await post('/auth/logout',{})}catch{}location.replace('/')};
 $('refreshStudents').onclick=loadRisks;
 $('createStudent').onclick=async()=>{try{await post('/api/students',{name:val('sName'),grade:val('sGrade'),program:val('sProgram'),enrolled_at:val('sEnrolled'),notes:val('sNotes')||undefined});msg('studentCreateMsg','학생이 등록됐습니다.');$('sName').value='';$('sGrade').value='';$('sNotes').value='';await Promise.all([loadRisks(),loadBrief()])}catch(e){msg('studentCreateMsg',friendly(e),false)}};
 $('createLead').onclick=async()=>{try{const due=val('lDue');await post('/api/leads',{child_name:val('lName'),grade:val('lGrade')||undefined,english_experience:val('lExperience')||undefined,goal:val('lGoal')||undefined,source:val('lSource')||undefined,followup_due_at:due?new Date(due).toISOString():undefined});msg('leadCreateMsg','신규 문의가 등록됐습니다.');$('lName').value='';await Promise.all([loadLeads(),loadBrief()])}catch(e){msg('leadCreateMsg',friendly(e),false)}};
 $('saveProfile').onclick=async()=>{try{const d=await post('/api/promo/profile',{academy_name:val('pAcademy'),neighborhood:val('pNeighborhood'),consultation_cta:val('pCta'),naver_blog_url:val('pNaver'),instagram_handle:val('pInstagram'),daangn_profile:val('pDaangn')});renderMissing(d.missing||[]);msg('profileMsg','홍보 기본정보를 저장했습니다.')}catch(e){msg('profileMsg',friendly(e),false)}};
 $('makeMission').onclick=async()=>{const b=$('makeMission');b.disabled=true;b.textContent='AI 홍보실장이 이번 주 작전 짜는 중…';$('missionResult').style.display='block';$('missionResult').textContent='빈자리·유입성과·채널을 분석하고 있습니다.';try{const channels=[];if($('chNaver').checked)channels.push('NAVER_BLOG');if($('chInstagram').checked)channels.push('INSTAGRAM');if($('chDaangn').checked)channels.push('DAANGN');const d=await post('/api/promo/mission',{goal_students:Number(val('goalStudents')||5),target_segment:val('targetSegment')||undefined,channels});currentMission=d.id;$('missionResult').textContent=d.mission_text;renderMissing(d.missing_profile||[]);renderNeeds(d.needs||[]);toast('이번 주 홍보작전이 완성됐습니다.')}catch(e){$('missionResult').textContent='생성 실패: '+friendly(e)}finally{b.disabled=false;b.textContent='이번 주 홍보작전 짜기'}};
 document.querySelectorAll('[data-make-post]').forEach(b=>b.onclick=()=>makePost(b.dataset.makePost));
}
$('sEnrolled').value=seoulDate();bind();window.__AI_OFFICE_READY__=true;document.documentElement.dataset.appReady='true';Promise.allSettled([health(),loadBrief()]).then(()=>{if(!window.__AI_OFFICE_DATA_READY__)console.warn('AI_OFFICE_DATA_NOT_READY')});
})();`;