import {CLIENT_JS as V6} from './client-v6.js';

const OLD_ACTIONS=`'<div style="display:flex;justify-content:flex-end;margin-top:10px"><button class="ghost" type="button" data-delete-student="'+esc(s.id||'')+'" data-student-name="'+esc(s.name||'학생')+'">학생 삭제</button></div></div>'`;
const NEW_ACTIONS=`'<div style="display:flex;gap:8px;justify-content:flex-end;margin-top:10px"><button class="ghost" type="button" data-edit-student="'+esc(s.id||'')+'">수정</button><button class="ghost" type="button" data-delete-student="'+esc(s.id||'')+'" data-student-name="'+esc(s.name||'학생')+'">삭제</button></div><div data-student-edit-panel="'+esc(s.id||'')+'" style="display:none;margin-top:10px;padding:12px;border:1px solid #e3e7f1;border-radius:14px;background:#fbfcff"><label>학생 이름</label><input data-edit-name value="'+esc(s.name||'')+'"><label>학년</label><input data-edit-grade value="'+esc(s.grade||'')+'"><label>과정</label><select data-edit-program><option value="MUEM" '+(s.program==='MUEM'?'selected':'')+'>뮤엠영어</option><option value="NOPIGOM" '+(s.program==='NOPIGOM'?'selected':'')+'>노피곰</option><option value="BOTH" '+(s.program==='BOTH'?'selected':'')+'>둘 다</option></select><label>등록일</label><input type="date" data-edit-enrolled value="'+esc(s.enrolled_at||'')+'"><label>원장 메모</label><textarea data-edit-notes>'+esc(s.notes||'')+'</textarea><div style="display:flex;gap:8px;justify-content:flex-end;margin-top:10px"><button class="ghost" type="button" data-cancel-student="'+esc(s.id||'')+'">취소</button><button class="secondary" type="button" data-save-student="'+esc(s.id||'')+'">저장</button></div></div></div>'`;

const OLD_CLICK=`document.addEventListener('click',e=>{const b=e.target.closest?.('[data-delete-student]');if(b)deleteStudentFromCard(b)});`;
const NEW_CLICK=`document.addEventListener('click',e=>{const edit=e.target.closest?.('[data-edit-student]');if(edit){const row=edit.closest('.row'),panel=row?.querySelector('[data-student-edit-panel]');if(panel){panel.style.display='block';panel.querySelector('[data-edit-name]')?.focus()}return}const cancel=e.target.closest?.('[data-cancel-student]');if(cancel){const panel=cancel.closest('[data-student-edit-panel]');if(panel)panel.style.display='none';return}const save=e.target.closest?.('[data-save-student]');if(save){saveStudentFromCard(save);return}const del=e.target.closest?.('[data-delete-student]');if(del)deleteStudentFromCard(del)});`;

export const CLIENT_JS=V6
  .replace(OLD_ACTIONS,NEW_ACTIONS)
  .replace("async function deleteStudentFromCard(button){",`async function saveStudentFromCard(button){const row=button.closest('.row'),id=button?.dataset?.saveStudent||'';if(!row||!id)return;const name=(row.querySelector('[data-edit-name]')?.value||'').trim(),grade=(row.querySelector('[data-edit-grade]')?.value||'').trim(),program=row.querySelector('[data-edit-program]')?.value||'',enrolled_at=row.querySelector('[data-edit-enrolled]')?.value||'',notes=(row.querySelector('[data-edit-notes]')?.value||'').trim();if(!name){toast('학생 이름을 입력해주세요.');return}if(!grade){toast('학년을 입력해주세요.');return}button.disabled=true;button.textContent='저장 중…';try{await api('/api/students/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({name,grade,program,enrolled_at:enrolled_at||undefined,notes:notes||undefined})});toast(name+' 학생 정보를 수정했습니다.');await Promise.all([loadRisks(),loadBrief()])}catch(e){toast(friendly(e));button.disabled=false;button.textContent='저장'}}\nasync function deleteStudentFromCard(button){`)
  .replace(OLD_CLICK,NEW_CLICK);
