import {CLIENT_JS as V3} from './client-v3.js';

export const CLIENT_JS=V3
  .replace("INTERNAL_ERROR:'처리 중 문제가 생겼습니다. 잠시 후 다시 시도해주세요.'", "AI_QUOTA_EXHAUSTED:'오늘의 무료 AI 사용량을 모두 사용했습니다. 다음 일일 초기화(한국시간 오전 9시) 후 다시 시도하거나 AI 사용 플랜을 연결해주세요.',INTERNAL_ERROR:'처리 중 문제가 생겼습니다. 잠시 후 다시 시도해주세요.'")
  .replace("let currentMission=null,currentNeeds=[];", "let currentMission=null,currentNeeds=[],currentRun=null;")
  .replace("$('pNaver').value=d.profile?.naver_blog_url||'';", "$('pYoutube').value=d.profile?.youtube_channel_url||'';$('pNaver').value=d.profile?.naver_blog_url||'';")
  .replace("naver_blog_url:val('pNaver'),instagram_handle:val('pInstagram'),daangn_profile:val('pDaangn')", "youtube_channel_url:val('pYoutube'),naver_blog_url:val('pNaver'),instagram_handle:val('pInstagram'),daangn_profile:val('pDaangn')")
  .replace("const channels=[];if($('chNaver').checked)channels.push('NAVER_BLOG');if($('chInstagram').checked)channels.push('INSTAGRAM');if($('chDaangn').checked)channels.push('DAANGN');", "const channels=[];if($('chYoutube')?.checked)channels.push('YOUTUBE');if($('chNaver').checked)channels.push('NAVER_BLOG');if($('chInstagram').checked)channels.push('INSTAGRAM');if($('chDaangn').checked)channels.push('DAANGN');")
  .replace("if(d.latest_mission){currentMission=d.latest_mission.id;$('missionResult').style.display='block';$('missionResult').textContent=d.latest_mission.mission_text;renderNeeds(d.latest_mission.needs||[])}", "if(d.latest_mission){currentMission=d.latest_mission.id;$('missionResult').style.display='block';$('missionResult').textContent=d.latest_mission.mission_text;renderNeeds(d.latest_mission.needs||[]);if($('startProduction'))$('startProduction').disabled=false}")
  .replace("currentMission=d.id;$('missionResult').textContent=d.mission_text;", "currentMission=d.id;$('missionResult').textContent=d.mission_text;if($('startProduction'))$('startProduction').disabled=false;")
  .replace("await post('/api/promo/assets/generate',{mission_id:currentMission,purpose:n.purpose,channel:n.channel,width:n.width,height:n.height,prompt_hint:n.prompt_hint});toast('홍보 이미지가 만들어졌습니다.');", "const d=await post('/api/promo/assets/generate',{mission_id:currentMission,purpose:n.purpose,channel:n.channel,width:n.width,height:n.height,prompt_hint:n.prompt_hint});toast(d.reused?'기존 학원 홍보자산을 재사용했습니다.':'새 홍보 이미지가 만들어졌습니다.');")
  .replace("function bind(){", `function renderProduction(run){const box=$('productionStatus');if(!box||!run)return;box.style.display='block';const total=Number(run.total_items||run.stats?.total||0),done=Number(run.done_items||run.stats?.done||0),failed=Number(run.failed_items||run.stats?.failed||0);box.textContent='제작 상태: '+String(run.status||'QUEUED')+' · 완료 '+done+'/'+total+' · 실패 '+failed+(run.status==='DONE'?'\\n이번 주 제작이 모두 완료됐습니다.':'\\n앱을 닫아도 백그라운드 제작이 계속됩니다.');}
async function startProduction(){if(!currentMission){toast('먼저 이번 주 홍보작전을 만들어주세요.');return}const b=$('startProduction');b.disabled=true;b.textContent='제작 큐 준비 중…';try{const run=await post('/api/promo/missions/'+encodeURIComponent(currentMission)+'/run',{});currentRun=run.id;renderProduction(run);const first=await post('/api/promo/runs/'+encodeURIComponent(currentRun)+'/process',{max_items:1});renderProduction(first);await loadPromo();toast(first.status==='DONE'?'이번 주 제작이 완료됐습니다.':'제작을 시작했습니다. 백그라운드에서 계속 진행됩니다.')}catch(e){msg('productionStatus',friendly(e),false)}finally{b.disabled=false;b.textContent='이번 주 제작 전체 시작'}}
function bind(){`)
  .replace(" $('refreshStudents').onclick=loadRisks;", " if($('startProduction'))$('startProduction').onclick=startProduction;\n $('refreshStudents').onclick=loadRisks;")
  .replace("window.__AI_OFFICE_READY__=true;", "window.__AI_OFFICE_PROMO_V6__=true;window.__AI_OFFICE_READY__=true;");
