import {CLIENT_JS as V12} from './client-v12.js';

const OLD_RENDER=`function renderAssets(assets=[]){$('assetGallery').innerHTML=assets.length?assets.map(a=>'<div class="asset"><img src="'+esc(a.url)+'" alt="'+esc(a.purpose||'홍보 이미지')+'"><div><b>'+esc(a.purpose||'홍보 이미지')+'</b><br>'+esc(a.channel||'')+' · '+(a.width||'')+'×'+(a.height||'')+'</div></div>').join(''):'<div class="empty">아직 생성된 홍보 이미지가 없습니다.</div>'}`;
const NEW_RENDER=`function renderAssets(assets=[]){$('assetGallery').innerHTML=assets.length?assets.map(a=>{const video=a.kind==='VIDEO'||String(a.mime_type||'').startsWith('video/'),media=video?'<video controls preload="metadata" playsinline src="'+esc(a.url)+'"></video>':'<img src="'+esc(a.url)+'" alt="'+esc(a.purpose||'홍보 이미지')+'">',size=(a.width&&a.height)?' · '+a.width+'×'+a.height:'';return '<div class="asset">'+media+'<div><b>'+esc(a.purpose||(video?'학원 영상':'홍보 이미지'))+'</b><br>'+esc(a.channel||'GENERAL')+size+'<br><span class="mediaTag">'+(video?'동영상':'사진')+'</span></div></div>'}).join(''):'<div class="empty">아직 저장된 홍보 자산이 없습니다.</div>'}`;

const GALLERY_FUNCTIONS=`async function galleryMediaMeta(file){try{if(String(file.type||'').startsWith('image/')&&window.createImageBitmap){const bmp=await createImageBitmap(file);const out={width:bmp.width||0,height:bmp.height||0};bmp.close?.();return out}if(String(file.type||'').startsWith('video/'))return await new Promise(resolve=>{const url=URL.createObjectURL(file),v=document.createElement('video'),done=()=>{const out={width:v.videoWidth||0,height:v.videoHeight||0};URL.revokeObjectURL(url);resolve(out)};v.preload='metadata';v.onloadedmetadata=done;v.onerror=done;v.src=url;setTimeout(done,3000)});}catch{}return {width:0,height:0}}\nfunction galleryUploadError(code){return ({UNSUPPORTED_MEDIA_TYPE:'사진 또는 동영상 파일만 선택해주세요.',MEDIA_SIZE_REQUIRED:'파일 크기를 확인하지 못했습니다.',IMAGE_TOO_LARGE:'사진은 한 장당 20MB 이하로 선택해주세요.',VIDEO_TOO_LARGE:'동영상은 한 개당 80MB 이하로 선택해주세요.',PROMO_ASSETS_NOT_BOUND:'홍보 자산 저장소 연결을 확인해주세요.'})[code]||friendly(new Error(code))}\nasync function uploadGalleryFiles(fileList){const files=[...(fileList||[])];if(!files.length)return;const status=$('galleryUploadStatus'),input=$('galleryMedia'),purposeBase=val('galleryPurpose'),channel=val('galleryChannel')||'GENERAL';status.style.display='block';let ok=0;for(let i=0;i<files.length;i++){const file=files[i],mime=String(file.type||''),isVideo=mime.startsWith('video/'),isImage=mime.startsWith('image/'),limit=isVideo?80*1024*1024:20*1024*1024;if(!isImage&&!isVideo){status.textContent=(i+1)+'/'+files.length+' · '+file.name+' · 사진/동영상만 가능합니다.';continue}if(file.size>limit){status.textContent=(i+1)+'/'+files.length+' · '+file.name+' · '+(isVideo?'80MB':'20MB')+'를 초과했습니다.';continue}status.textContent=(i+1)+'/'+files.length+' · '+file.name+' 업로드 중…';try{const meta=await galleryMediaMeta(file),headers={'x-csrf-token':csrf,'content-type':file.type||'application/octet-stream','x-file-size':String(file.size),'x-file-name':encodeURIComponent(file.name||''),'x-channel':channel,'x-purpose':encodeURIComponent(purposeBase||(isVideo?'학원 갤러리 영상':'학원 갤러리 사진'))};if(currentMission)headers['x-mission-id']=encodeURIComponent(currentMission);if(meta.width)headers['x-width']=String(meta.width);if(meta.height)headers['x-height']=String(meta.height);const r=await fetch('/api/promo/assets/upload',{method:'POST',headers,body:file});const d=await r.json().catch(()=>({ok:false,error:'INVALID_RESPONSE'}));if(r.status===401){location.replace('/');throw new Error('AUTH_REQUIRED')}if(!r.ok||d.ok===false)throw new Error(d.error||d.detail||('HTTP '+r.status));ok++;status.textContent=(i+1)+'/'+files.length+' · '+file.name+' 저장 완료'}catch(e){status.textContent=(i+1)+'/'+files.length+' · '+file.name+' · '+galleryUploadError(String(e?.message||e))}}if(input)input.value='';await loadPromo();toast(ok+'개 자산을 갤러리에서 가져왔습니다.');status.textContent='완료 '+ok+'/'+files.length+' · 학원 전용 자산으로 저장했습니다.'}\n`;

let PATCHED=V12.replace(OLD_RENDER,NEW_RENDER);
if(PATCHED===V12)throw new Error('GALLERY_ASSET_RENDER_PATCH_MISSING');
PATCHED=PATCHED.replace('function bind(){',GALLERY_FUNCTIONS+`function bind(){if($('pickGalleryMedia'))$('pickGalleryMedia').onclick=()=>$('galleryMedia')?.click();if($('galleryMedia'))$('galleryMedia').onchange=e=>uploadGalleryFiles(e.target.files);`);
if(!PATCHED.includes("/api/promo/assets/upload")||!PATCHED.includes("$('pickGalleryMedia').onclick")||!PATCHED.includes('<video controls'))throw new Error('GALLERY_UPLOAD_HANDLER_PATCH_MISSING');
new Function(PATCHED);
export const CLIENT_JS=PATCHED;
