pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'KYouTubeFree'
include ':app'
include ':whisper'
project(':whisper').projectDir = file('vendor/whisper.cpp/examples/whisper.android/lib')
