import {chromium} from 'playwright';
const base=(process.env.DEPLOY_URL||'').replace(/\/$/,'');const password=process.env.ADMIN_PASSWORD||'';if(!base)throw new Error('DEPLOY_URL_REQUIRED');if(password.length<12)throw new Error('ADMIN_PASSWORD_REQUIRED');
const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message||String(e)));
let logged=false;
async function internalPost(path){return page.evaluate(async p=>{const csrf=document.querySelector('meta[name="csrf-token"]')?.content||'';const r=await fetch(p,{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf},body:'{}'});return {status:r.status,body:await r.json().catch(()=>null)}},path)}
try{
 await page.goto(base+'/',{waitUntil:'domcontentloaded',timeout:30000});await page.locator('#pw').fill(password);await Promise.all([page.waitForURL(base+'/',{timeout:30000}),page.locator('#login').click()]);logged=true;await page.waitForFunction(()=>window.__AI_OFFICE_READY__===true&&window.__AI_OFFICE_PROMO_V6__===true,{timeout:20000});await page.waitForFunction(()=>window.__AI_OFFICE_DATA_READY__===true,{timeout:30000});
 const system=await page.locator('#systemStatus').innerText();if(!system.includes('연결 정상'))throw new Error('SYSTEM_NOT_READY:'+system);
 await internalPost('/api/internal/p3-cleanup');const fixture=await internalPost('/api/internal/p3-ui-fixture');if(!(fixture.status===201&&fixture.body?.data?.ai_calls===0))throw new Error('P3_UI_FIXTURE_FAILED:'+JSON.stringify(fixture));
 await page.locator('.mobilebar [data-view="students"]').click();await page.locator('#students').waitFor({state:'visible'});await page.locator('[data-toggle="studentCreate"]').click();await page.locator('#studentCreate').waitFor({state:'visible'});await page.locator('#sName').fill('P3 UI 검수');await page.locator('#sGrade').fill('초3');const date=await page.locator('#sEnrolled').inputValue();if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('SEOUL_DATE_NOT_SET');
 await page.locator('.mobilebar [data-view="leads"]').click();await page.locator('#leads').waitFor({state:'visible'});await page.locator('[data-toggle="leadCreate"]').click();await page.locator('#leadCreate').waitFor({state:'visible'});await page.locator('#lName').fill('P3 상담 검수');
 await page.locator('.mobilebar [data-view="recruitment"]').click();await page.locator('#recruitment').waitFor({state:'visible'});await page.waitForFunction(()=>document.getElementById('missionResult')?.textContent.includes('P3 모바일 검수용'),{timeout:20000});
 if(!(await page.locator('#pYoutube').isVisible()))throw new Error('YOUTUBE_PROFILE_FIELD_MISSING');for(const id of ['chYoutube','chNaver','chInstagram','chDaangn'])if(!(await page.locator('#'+id).isChecked()))throw new Error('CHANNEL_NOT_DEFAULT:'+id);
 await page.waitForSelector('[data-gen-asset]',{timeout:10000});const firstNeed=await page.locator('#assetNeeds .need').first().innerText();if(!firstNeed.includes('YOUTUBE'))throw new Error('YOUTUBE_ASSET_NEED_MISSING:'+firstNeed);if(!(await page.locator('[data-make-post="YOUTUBE"]').isVisible()))throw new Error('YOUTUBE_POST_BUTTON_MISSING');
 if(await page.locator('#startProduction').isDisabled())throw new Error('START_PRODUCTION_DISABLED_FOR_FIXTURE');await page.locator('#startProduction').click();await page.waitForFunction(()=>{const x=document.getElementById('productionStatus');return x&&x.style.display!=='none'&&x.textContent.includes('완료 1/1')&&x.textContent.includes('모두 완료')&&!x.classList.contains('error')},{timeout:30000});const productionText=await page.locator('#productionStatus').innerText();
 if(errors.length)throw new Error('BROWSER_JS_ERRORS:'+JSON.stringify(errors));
 console.log(JSON.stringify({ok:true,base,viewport:'390x844',login:true,js_ready:true,promo_v6_ready:true,data_ready:true,tabs:{today:true,students:true,leads:true,recruitment:true},student_form:true,lead_form:true,youtube_profile_field:true,four_channels_checked:true,p3_fixture:true,fixture_ai_calls:0,youtube_asset_need:true,youtube_post_button:true,whole_week_production_clicked:true,production_status:productionText,system_status:system,seoul_date:date},null,2));
}finally{
 if(logged){try{await internalPost('/api/internal/p3-cleanup')}catch{}}
 await browser.close();
}
