import {chromium} from 'playwright';
const base=(process.env.DEPLOY_URL||'').replace(/\/$/,'');const password=process.env.ADMIN_PASSWORD||'';if(!base)throw new Error('DEPLOY_URL_REQUIRED');if(password.length<12)throw new Error('ADMIN_PASSWORD_REQUIRED');
const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message||String(e)));
let logged=false;
try{
 await page.goto(base+'/',{waitUntil:'domcontentloaded',timeout:30000});await page.locator('#pw').fill(password);await Promise.all([page.waitForURL(base+'/',{timeout:30000}),page.locator('#login').click()]);logged=true;await page.waitForFunction(()=>window.__AI_OFFICE_READY__===true&&window.__AI_OFFICE_PROMO_V6__===true,{timeout:20000});await page.waitForFunction(()=>window.__AI_OFFICE_DATA_READY__===true,{timeout:30000});
 const system=await page.locator('#systemStatus').innerText();if(!system.includes('연결 정상'))throw new Error('SYSTEM_NOT_READY:'+system);
 await page.locator('.mobilebar [data-view="students"]').click();await page.locator('#students').waitFor({state:'visible'});await page.locator('[data-toggle="studentCreate"]').click();await page.locator('#studentCreate').waitFor({state:'visible'});await page.locator('#sName').fill('P3 UI 검수');await page.locator('#sGrade').fill('초3');const date=await page.locator('#sEnrolled').inputValue();if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('SEOUL_DATE_NOT_SET');
 await page.locator('.mobilebar [data-view="leads"]').click();await page.locator('#leads').waitFor({state:'visible'});await page.locator('[data-toggle="leadCreate"]').click();await page.locator('#leadCreate').waitFor({state:'visible'});await page.locator('#lName').fill('P3 상담 검수');
 await page.locator('.mobilebar [data-view="recruitment"]').click();await page.locator('#recruitment').waitFor({state:'visible'});if(!(await page.locator('#pYoutube').isVisible()))throw new Error('YOUTUBE_PROFILE_FIELD_MISSING');if(!(await page.locator('#chYoutube').isChecked()))throw new Error('YOUTUBE_CHANNEL_NOT_DEFAULT');await page.locator('#targetSegment').fill('P3 모바일 모집 검수');await page.locator('#goalStudents').fill('1');await page.locator('#makeMission').click();await page.waitForFunction(()=>{const x=document.getElementById('missionResult');return x&&x.style.display!=='none'&&x.textContent.length>250&&!x.textContent.includes('분석하고 있습니다')&&!x.textContent.includes('생성 실패')},{timeout:100000});
 await page.waitForSelector('[data-gen-asset]',{timeout:10000});const firstNeed=await page.locator('#assetNeeds .need').first().innerText();if(!firstNeed.includes('YOUTUBE'))throw new Error('YOUTUBE_ASSET_NOT_FIRST:'+firstNeed);await page.locator('[data-gen-asset]').first().click();await page.waitForFunction(()=>document.querySelectorAll('#assetGallery img').length>0,{timeout:130000});
 await page.locator('[data-make-post="YOUTUBE"]').click();await page.waitForFunction(()=>{const x=document.getElementById('postResult');return x&&x.style.display!=='none'&&x.textContent.length>300&&!x.textContent.includes('완성 원고를 만들고 있습니다')&&!x.textContent.includes('생성 실패')},{timeout:100000});const youtubeChars=(await page.locator('#postResult').innerText()).length;
 await page.locator('[data-make-post="INSTAGRAM"]').click();await page.waitForFunction(()=>{const x=document.getElementById('postResult');return x&&x.style.display!=='none'&&x.textContent.length>150&&!x.textContent.includes('완성 원고를 만들고 있습니다')&&!x.textContent.includes('생성 실패')},{timeout:100000});
 if(errors.length)throw new Error('BROWSER_JS_ERRORS:'+JSON.stringify(errors));
 console.log(JSON.stringify({ok:true,base,viewport:'390x844',login:true,js_ready:true,promo_v6_ready:true,data_ready:true,tabs:{today:true,students:true,leads:true,recruitment:true},student_form:true,lead_form:true,youtube_profile_field:true,youtube_channel_checked:true,promo_mission:true,youtube_asset_need:true,promo_image_visible:true,youtube_package_ready:true,youtube_chars:youtubeChars,instagram_copy_ready:true,system_status:system,seoul_date:date},null,2));
}finally{
 if(logged){try{await page.evaluate(async()=>{const csrf=document.querySelector('meta[name="csrf-token"]')?.content||'';await fetch('/api/internal/p3-cleanup',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf},body:'{}'})})}catch{}}
 await browser.close();
}
