const base=(process.env.DEPLOY_URL||'').replace(/\/$/,'');const adminPassword=process.env.ADMIN_PASSWORD||'';if(!base)throw new Error('DEPLOY_URL_REQUIRED');if(adminPassword.length<12)throw new Error('ADMIN_PASSWORD_REQUIRED');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const timed=(url,opt={},ms=20000)=>fetch(url,{...opt,signal:AbortSignal.timeout(ms)});const parse=async r=>{const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{}return {status:r.status,ok:r.ok,body,text,headers:r.headers}};const origin=new URL(base).origin;
async function ready(){let last='';for(let i=1;i<=8;i++){try{const [h,p,s]=await Promise.all([timed(base+'/health'),timed(base+'/preflight'),timed(base+'/auth/status')]);const H=await parse(h),P=await parse(p),S=await parse(s);if(H.body?.ok&&H.body?.version==='0.5.0'&&H.body?.db&&H.body?.ai&&H.body?.r2&&H.body?.auth&&P.body?.ok&&P.body?.checks?.r2&&S.body?.data?.configured)return {H:H.body,P:P.body}}catch(e){last=e.message}await sleep(3500)}throw new Error('READINESS_FAILED:'+last)}
const R=await ready();
const loginRes=await timed(base+'/auth/login',{method:'POST',headers:{'content-type':'application/json','origin':origin},body:JSON.stringify({password:adminPassword})},15000);const L=await parse(loginRes.clone());const cookie=loginRes.headers.get('set-cookie')?.split(';')[0]||'',csrf=L.body?.data?.csrf||'';if(!(L.ok&&cookie&&csrf))throw new Error('LOGIN_FAILED');
const auth={cookie,accept:'application/json'},write={cookie,'x-csrf-token':csrf,'content-type':'application/json',accept:'application/json',origin};const post=async(path,body,ms=30000)=>parse(await timed(base+path,{method:'POST',headers:write,body:JSON.stringify(body)},ms));
await post('/api/internal/p3-cleanup',{});
let missionId=null,assetId=null;
try{
 const target=await post('/api/recruitment/targets',{id:'e2e-target',segment:'P3 모집 검수',program:'MUEM',capacity:1,active_students:0,desired_new_students:1,priority:0});if(!(target.ok&&target.body?.data?.open_seats===1))throw new Error('TARGET_FAILED');
 const mission=await post('/api/promo/mission',{goal_students:1,target_segment:'P3 모집 검수',channels:['NAVER_BLOG','INSTAGRAM','DAANGN']},70000);missionId=mission.body?.data?.id;if(!(mission.ok&&missionId&&mission.body.data.needs?.length>=3&&mission.body.data.mission_text?.length>200))throw new Error('MISSION_FAILED:'+mission.text);
 const asset=await post('/api/promo/assets/generate',{mission_id:missionId,purpose:'P3 이미지 검수',channel:'INSTAGRAM',width:512,height:512,prompt_hint:'깔끔한 영어학원 책상과 교재, 자연광, 글자 없음'},90000);assetId=asset.body?.data?.id;if(!(asset.ok&&assetId))throw new Error('IMAGE_GENERATE_FAILED:'+asset.text);
 const img=await timed(base+'/api/promo/assets/'+encodeURIComponent(assetId),{headers:auth},20000);const bytes=await img.arrayBuffer();if(!(img.ok&&(img.headers.get('content-type')||'').startsWith('image/')&&bytes.byteLength>5000))throw new Error('R2_IMAGE_READ_FAILED');
 const insta=await post('/api/promo/posts',{mission_id:missionId,channel:'INSTAGRAM'},70000);if(!(insta.ok&&insta.body?.data?.body?.length>150&&!insta.body.data.body.includes('[연락처]')))throw new Error('INSTAGRAM_POST_FAILED');
 const blog=await post('/api/promo/posts',{mission_id:missionId,channel:'NAVER_BLOG'},70000);if(!(blog.ok&&blog.body?.data?.body?.length>300&&!blog.body.data.body.includes('[연락처]')))throw new Error('NAVER_POST_FAILED');
 const dash=await parse(await timed(base+'/api/promo/dashboard',{headers:auth},20000));if(!(dash.ok&&dash.body?.data?.latest_mission?.id===missionId&&dash.body?.data?.assets?.some(x=>x.id===assetId)))throw new Error('PROMO_DASHBOARD_FAILED');
 console.log(JSON.stringify({ok:true,base,health:R.H,preflight:R.P,promo:{mission:true,needs:mission.body.data.needs.length,image_generated:true,r2_image_bytes:bytes.byteLength,instagram_ready:true,naver_blog_ready:true,no_placeholders:true}},null,2));
}finally{const clean=await post('/api/internal/p3-cleanup',{});if(!clean.ok)console.warn('P3_CLEANUP_FAILED',clean.text)}
