const base=(process.env.DEPLOY_URL||'').replace(/\/$/,'');const adminPassword=process.env.ADMIN_PASSWORD||'';if(!base)throw new Error('DEPLOY_URL_REQUIRED');if(adminPassword.length<12)throw new Error('ADMIN_PASSWORD_REQUIRED');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const timed=(url,opt={},ms=20000)=>fetch(url,{...opt,signal:AbortSignal.timeout(ms)});const parse=async r=>{const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{}return {status:r.status,ok:r.ok,body,text,headers:r.headers}};const origin=new URL(base).origin;
async function ready(){let last='';for(let i=1;i<=8;i++){try{const [h,p,s]=await Promise.all([timed(base+'/health'),timed(base+'/preflight'),timed(base+'/auth/status')]);const H=await parse(h),P=await parse(p),S=await parse(s);if(H.body?.ok&&H.body?.version==='0.6.0'&&H.body?.db&&H.body?.ai&&H.body?.r2&&H.body?.auth&&H.body?.promoEngine==='embedded-p1-style-v1'&&H.body?.backgroundPromo===true&&H.body?.aiRetry===true&&P.body?.ok&&P.body?.checks?.r2&&P.body?.checks?.embeddedPromoEngine&&P.body?.checks?.backgroundPromo&&P.body?.checks?.aiRetry&&S.body?.data?.configured)return {H:H.body,P:P.body}}catch(e){last=e.message}await sleep(3000)}throw new Error('READINESS_FAILED:'+last)}
const R=await ready();
const denied=await parse(await timed(base+'/api/briefing',{headers:{accept:'application/json'}},15000));if(denied.status!==401)throw new Error('UNAUTHENTICATED_API_NOT_BLOCKED:'+denied.status);
const loginRes=await timed(base+'/auth/login',{method:'POST',headers:{'content-type':'application/json','origin':origin},body:JSON.stringify({password:adminPassword})},15000);const L=await parse(loginRes.clone()),cookie=loginRes.headers.get('set-cookie')?.split(';')[0]||'',csrf=L.body?.data?.csrf||'';if(!(L.ok&&cookie&&csrf))throw new Error('LOGIN_FAILED');
const auth={cookie,accept:'application/json'},write={cookie,'x-csrf-token':csrf,'content-type':'application/json',accept:'application/json',origin};const post=async(path,body,ms=30000)=>parse(await timed(base+path,{method:'POST',headers:write,body:JSON.stringify(body)},ms));
await post('/api/internal/p3-cleanup',{});
try{
 const target=await post('/api/recruitment/targets',{id:'e2e-target',segment:'P3 경량 검수',program:'MUEM',capacity:1,active_students:0,desired_new_students:1,priority:0});if(!(target.ok&&target.body?.data?.open_seats===1))throw new Error('TARGET_D1_FAILED:'+target.text);
 const diag=await parse(await timed(base+'/api/internal/p3-diagnostic',{headers:auth},90000)),d=diag.body?.data;if(!diag.ok||!d)throw new Error('DIAGNOSTIC_HTTP_FAILED:'+diag.text);if(!d.ai_probe?.ok){const m=String(d.ai_probe?.error?.message||'');if(m.toLowerCase().includes('allocation')||m.toLowerCase().includes('exhausted'))throw new Error('EXTERNAL_AI_QUOTA_BLOCKED: Cloudflare Workers AI daily allocation exhausted; D1/R2/deploy infrastructure is healthy but AI probe cannot complete');throw new Error('AI_PROBE_FAILED:'+JSON.stringify(d.ai_probe));}if(!(d.db_targets?.ok&&d.r2_probe?.ok&&d.r2_probe?.data?.write&&d.r2_probe?.data?.read&&d.ai_binding?.ok&&d.ai_probe?.data?.has_text))throw new Error('RESOURCE_DIAGNOSTIC_FAILED:'+JSON.stringify(d));
 const fixture=await post('/api/internal/p3-ui-fixture',{});const missionId=fixture.body?.data?.mission_id,runId=fixture.body?.data?.run_id;if(!(fixture.ok&&missionId&&runId&&fixture.body?.data?.ai_calls===0))throw new Error('P3_FIXTURE_FAILED:'+fixture.text);
 const dash=await parse(await timed(base+'/api/promo/dashboard',{headers:auth},20000));const caps=dash.body?.data?.channel_capabilities||{};if(!(dash.ok&&dash.body?.data?.latest_mission?.id===missionId&&dash.body?.data?.engine?.asset_reuse===true&&dash.body?.data?.engine?.resumable_queue===true&&caps.YOUTUBE&&caps.INSTAGRAM&&caps.NAVER_BLOG&&caps.DAANGN))throw new Error('PROMO_DASHBOARD_FAILED:'+dash.text.slice(0,1000));
 const run=await post('/api/promo/missions/'+encodeURIComponent(missionId)+'/run',{});if(!(run.ok&&run.body?.data?.id===runId&&Number(run.body?.data?.total_items)===1))throw new Error('PRODUCTION_RUN_LOOKUP_FAILED:'+run.text);
 const processed=await post('/api/promo/runs/'+encodeURIComponent(runId)+'/process',{max_items:1});if(!(processed.ok&&processed.body?.data?.status==='DONE'&&Number(processed.body?.data?.done_items)===1&&Number(processed.body?.data?.failed_items)===0))throw new Error('PRODUCTION_PROCESS_FAILED:'+processed.text);
 const state=await parse(await timed(base+'/api/promo/runs/'+encodeURIComponent(runId),{headers:auth},15000));if(!(state.ok&&state.body?.data?.status==='DONE'&&state.body?.data?.items?.[0]?.status==='READY'))throw new Error('PRODUCTION_STATE_FAILED:'+state.text);
 console.log(JSON.stringify({ok:true,mode:'QUOTA_SAFE_DEPLOY_E2E',base,health:R.H,preflight:R.P,security:{unauth_blocked:true,login:true},resources:{d1:true,r2_write_read_delete:true,workers_ai_short_probe:true,ai_model:d.ai_binding.model},promo:{fixture_ai_calls:0,four_channel_capabilities:true,production_queue:true,production_done:true}},null,2));
}finally{const clean=await post('/api/internal/p3-cleanup',{});if(!clean.ok)console.warn('P3_CLEANUP_FAILED',clean.text)}
