const base=(process.env.DEPLOY_URL||'').replace(/\/$/,'');const adminPassword=process.env.ADMIN_PASSWORD||'';if(!base)throw new Error('DEPLOY_URL_REQUIRED');if(adminPassword.length<12)throw new Error('ADMIN_PASSWORD_REQUIRED');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const timed=(url,opt={},ms=20000)=>fetch(url,{...opt,signal:AbortSignal.timeout(ms)});const parse=async r=>{const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{}return {status:r.status,ok:r.ok,body,text,headers:r.headers}};const origin=new URL(base).origin;
async function ready(){let last='';for(let i=1;i<=8;i++){try{const [h,p,s]=await Promise.all([timed(base+'/health'),timed(base+'/preflight'),timed(base+'/auth/status')]);const H=await parse(h),P=await parse(p),S=await parse(s);if(H.body?.ok&&H.body?.version==='0.6.0'&&H.body?.db&&H.body?.ai&&H.body?.r2&&H.body?.auth&&H.body?.promoEngine==='embedded-p1-style-v1'&&H.body?.backgroundPromo===true&&H.body?.aiRetry===true&&P.body?.ok&&P.body?.checks?.r2&&P.body?.checks?.embeddedPromoEngine&&P.body?.checks?.backgroundPromo&&P.body?.checks?.aiRetry&&S.body?.data?.configured)return {H:H.body,P:P.body}}catch(e){last=e.message}await sleep(3500)}throw new Error('READINESS_FAILED:'+last)}
const R=await ready();
const loginRes=await timed(base+'/auth/login',{method:'POST',headers:{'content-type':'application/json','origin':origin},body:JSON.stringify({password:adminPassword})},15000);const L=await parse(loginRes.clone());const cookie=loginRes.headers.get('set-cookie')?.split(';')[0]||'',csrf=L.body?.data?.csrf||'';if(!(L.ok&&cookie&&csrf))throw new Error('LOGIN_FAILED');
const auth={cookie,accept:'application/json'},write={cookie,'x-csrf-token':csrf,'content-type':'application/json',accept:'application/json',origin};const post=async(path,body,ms=30000)=>parse(await timed(base+path,{method:'POST',headers:write,body:JSON.stringify(body)},ms));
await post('/api/internal/p3-cleanup',{});
let missionId=null,assetId=null,runId=null;
try{
 const target=await post('/api/recruitment/targets',{id:'e2e-target',segment:'P3 모집 검수',program:'MUEM',capacity:1,active_students:0,desired_new_students:1,priority:0});if(!(target.ok&&target.body?.data?.open_seats===1))throw new Error('TARGET_FAILED');
 const mission=await post('/api/promo/mission',{goal_students:1,target_segment:'P3 모집 검수',channels:['YOUTUBE','NAVER_BLOG','INSTAGRAM','DAANGN']},90000);missionId=mission.body?.data?.id;if(!(mission.ok&&missionId&&mission.body.data.channels?.includes('YOUTUBE')&&mission.body.data.needs?.length>=5&&mission.body.data.mission_text?.length>250)){const diag=await parse(await timed(base+'/api/internal/p3-diagnostic',{headers:auth},90000));throw new Error('MISSION_FAILED:'+mission.text+':DIAGNOSTIC:'+JSON.stringify(diag.body));}
 const firstNeed=mission.body.data.needs.find(x=>x.channel==='YOUTUBE'&&x.required)||mission.body.data.needs[0];if(!firstNeed)throw new Error('YOUTUBE_NEED_MISSING');
 const assetPayload={mission_id:missionId,purpose:firstNeed.purpose,channel:firstNeed.channel,width:firstNeed.width,height:firstNeed.height,prompt_hint:firstNeed.prompt_hint,target_segment:'P3 모집 검수'};
 const asset=await post('/api/promo/assets/generate',assetPayload,200000);assetId=asset.body?.data?.id;if(!(asset.ok&&assetId&&asset.body?.data?.reused===false))throw new Error('IMAGE_GENERATE_FAILED:'+asset.text);
 const reuse=await post('/api/promo/assets/generate',assetPayload,30000);if(!(reuse.ok&&reuse.body?.data?.reused===true&&reuse.body?.data?.id===assetId&&Number(reuse.body?.data?.match_score)>60))throw new Error('ASSET_REUSE_FAILED:'+reuse.text);
 const img=await timed(base+'/api/promo/assets/'+encodeURIComponent(assetId),{headers:auth},20000);const bytes=await img.arrayBuffer();if(!(img.ok&&(img.headers.get('content-type')||'').startsWith('image/')&&bytes.byteLength>5000))throw new Error('R2_IMAGE_READ_FAILED');
 const run=await post('/api/promo/missions/'+encodeURIComponent(missionId)+'/run',{},20000);runId=run.body?.data?.id;if(!(run.ok&&runId&&Number(run.body?.data?.total_items)>=9&&run.body?.data?.items?.some(x=>x.channel==='YOUTUBE')))throw new Error('PRODUCTION_RUN_CREATE_FAILED:'+run.text);
 const processed=await post('/api/promo/runs/'+encodeURIComponent(runId)+'/process',{max_items:1},45000);const processedFirst=processed.body?.data?.processed_now?.[0];if(!(processed.ok&&processed.body?.data?.processed_now?.length===1&&Number(processed.body?.data?.done_items)>=1&&processedFirst?.status==='READY'&&processedFirst?.reused===true))throw new Error('PRODUCTION_RUN_PROCESS_FAILED:'+processed.text);
 const runState=await parse(await timed(base+'/api/promo/runs/'+encodeURIComponent(runId),{headers:auth},20000));if(!(runState.ok&&runState.body?.data?.id===runId&&runState.body?.data?.items?.length===run.body.data.items.length))throw new Error('PRODUCTION_RUN_STATE_FAILED:'+runState.text);
 const yt=await post('/api/promo/posts',{mission_id:missionId,channel:'YOUTUBE'},90000);if(!(yt.ok&&yt.body?.data?.format==='SHORTS_PACKAGE'&&yt.body?.data?.body?.length>300&&!yt.body.data.body.includes('[연락처]')))throw new Error('YOUTUBE_POST_FAILED:'+yt.text);
 const insta=await post('/api/promo/posts',{mission_id:missionId,channel:'INSTAGRAM'},90000);if(!(insta.ok&&insta.body?.data?.body?.length>150&&!insta.body.data.body.includes('[연락처]')))throw new Error('INSTAGRAM_POST_FAILED:'+insta.text);
 const blog=await post('/api/promo/posts',{mission_id:missionId,channel:'NAVER_BLOG'},90000);if(!(blog.ok&&blog.body?.data?.body?.length>300&&!blog.body.data.body.includes('[연락처]')))throw new Error('NAVER_POST_FAILED:'+blog.text);
 const daangn=await post('/api/promo/posts',{mission_id:missionId,channel:'DAANGN'},90000);if(!(daangn.ok&&daangn.body?.data?.body?.length>120&&!daangn.body.data.body.includes('[연락처]')))throw new Error('DAANGN_POST_FAILED:'+daangn.text);
 const dash=await parse(await timed(base+'/api/promo/dashboard',{headers:auth},20000));const checks={http:dash.ok,latest_mission:dash.body?.data?.latest_mission?.id===missionId,asset:dash.body?.data?.assets?.some(x=>x.id===assetId)===true,asset_reuse:dash.body?.data?.engine?.asset_reuse===true,resumable_queue:dash.body?.data?.engine?.resumable_queue===true,youtube_capability:Boolean(dash.body?.data?.channel_capabilities?.YOUTUBE),profile_shape:Object.prototype.hasOwnProperty.call(dash.body?.data?.profile||{},'youtube_channel_url')};if(!Object.values(checks).every(Boolean))throw new Error('PROMO_DASHBOARD_FAILED:'+JSON.stringify(checks)+':'+dash.text.slice(0,1200));
 console.log(JSON.stringify({ok:true,base,health:R.H,preflight:R.P,promo:{mission:true,channels:4,needs:mission.body.data.needs.length,image_generated:true,asset_reuse:true,reuse_match_score:reuse.body.data.match_score,production_reused_asset:true,r2_image_bytes:bytes.byteLength,production_run:true,production_items:run.body.data.items.length,production_processed_one:true,youtube_ready:true,instagram_ready:true,naver_blog_ready:true,daangn_ready:true,dashboard_checks:checks,profile_untouched:true,no_placeholders:true}},null,2));
}finally{const clean=await post('/api/internal/p3-cleanup',{});if(!clean.ok)console.warn('P3_CLEANUP_FAILED',clean.text)}
