const base=(process.env.DEPLOY_URL||'').replace(/\/$/,'');const pw=process.env.ADMIN_PASSWORD||'';if(!base||pw.length<12)throw new Error('DEPLOY_URL_AND_ADMIN_PASSWORD_REQUIRED');
const parse=async r=>{const text=await r.text();let body=null;try{body=JSON.parse(text)}catch{}return {ok:r.ok,status:r.status,body,text}};const origin=new URL(base).origin;
const login=await fetch(base+'/auth/login',{method:'POST',headers:{'content-type':'application/json',origin},body:JSON.stringify({password:pw})});const L=await parse(login.clone()),cookie=login.headers.get('set-cookie')?.split(';')[0]||'',csrf=L.body?.data?.csrf||'';if(!(L.ok&&cookie&&csrf))throw new Error('LOGIN_FAILED');
const headers={cookie,'x-csrf-token':csrf,'content-type':'application/json',accept:'application/json',origin};const post=async(path,body,ms=120000)=>parse(await fetch(base+path,{method:'POST',headers,body:JSON.stringify(body),signal:AbortSignal.timeout(ms)}));
await post('/api/internal/p3-cleanup',{});try{
 const target=await post('/api/recruitment/targets',{id:'e2e-target',segment:'P3 Full AI 검수',program:'MUEM',capacity:1,active_students:0,desired_new_students:1,priority:0});if(!target.ok)throw new Error('TARGET_FAILED:'+target.text);
 const mission=await post('/api/promo/mission',{goal_students:1,target_segment:'P3 Full AI 검수',channels:['YOUTUBE','NAVER_BLOG','INSTAGRAM','DAANGN']});if(mission.body?.error==='AI_QUOTA_EXHAUSTED')throw new Error('EXTERNAL_AI_QUOTA_BLOCKED');const m=mission.body?.data;if(!(mission.ok&&m?.id&&m?.mission_text?.length>250))throw new Error('MISSION_FAILED:'+mission.text);
 const need=m.needs?.find(x=>x.channel==='YOUTUBE'&&x.required)||m.needs?.[0];if(!need)throw new Error('IMAGE_NEED_MISSING');const req={mission_id:m.id,purpose:need.purpose,channel:need.channel,width:need.width,height:need.height,prompt_hint:need.prompt_hint,target_segment:m.target_segment};
 const asset=await post('/api/promo/assets/generate',req,200000);if(asset.body?.error==='AI_QUOTA_EXHAUSTED')throw new Error('EXTERNAL_AI_QUOTA_BLOCKED');if(!(asset.ok&&asset.body?.data?.id))throw new Error('IMAGE_FAILED:'+asset.text);const reuse=await post('/api/promo/assets/generate',req);if(!(reuse.ok&&reuse.body?.data?.reused===true&&reuse.body?.data?.id===asset.body.data.id))throw new Error('REUSE_FAILED:'+reuse.text);
 const outputs={};for(const channel of ['YOUTUBE','INSTAGRAM','NAVER_BLOG','DAANGN']){const r=await post('/api/promo/posts',{mission_id:m.id,channel});if(r.body?.error==='AI_QUOTA_EXHAUSTED')throw new Error('EXTERNAL_AI_QUOTA_BLOCKED:'+channel);if(!(r.ok&&r.body?.data?.body?.length>120))throw new Error(channel+'_FAILED:'+r.text);outputs[channel]=r.body.data.body.length;}
 console.log(JSON.stringify({ok:true,mode:'FULL_AI_RELEASE_E2E',mission_chars:m.mission_text.length,image_generated:true,image_reused:true,channels:outputs},null,2));
}finally{await post('/api/internal/p3-cleanup',{})}
